myproject/urls.py
from django.conf.urls import patterns, url, include
from myproject import models, views
from django.conf import settings
from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
                url(r'^$', views.index, name='index'),
		url(r'^form/$', views.form, name='form'),
		url(r'^fm16/$', views.fm16, name='fm16'),
		#url(r'^about/$', views.about, name='about'),
		#url(r'^contactus/$', views.contact_form, name='contact_form'),
		
)

schooltax/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from registration.backends.default.views import RegistrationView

urlpatterns = [
    # Examples:
    # url(r'^$', 'kkpackers.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('myproject.urls')),
  
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/logout/$', 'accounts.views.logout_view', name='auth_logout'),
    url(r'^accounts/login/$', 'accounts.views.login_view', name='auth_login'),
    url(r'^accounts/register/$', 'accounts.views.registration_view', name='auth_register'),
    #url(r'^accounts/password/reset/$', 'accounts.views.password_reset', name='password_reset'),
    url(r'^accounts/address/add/$', 'accounts.views.add_user_address', name='add_user_address'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', 'accounts.views.activation_view', name='activation_view'),
    url(r'^accounts/password/reset/$', include('registration.backends.default.urls')),

]

if settings.DEBUG:
        urlpatterns += patterns(
                'django.views.static',
                (r'media/(?P<path>.*)',
                'serve',
                {'document_root': settings.MEDIA_ROOT}), )

accounts/models.py


from django.conf import settings
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.db import models
from django.template.loader import render_to_string

from localflavor.us.us_states import US_STATES
from smtplib import SMTP
# Create your models here.


# NEW_STATE = (
# 	('AB', "ABC STATE"),
# 	('BC', "BC STATE"),
# 	)

andhra_pradesh = "Andhra Pradesh"
telangana = "Telangana"
state_choices = ((andhra_pradesh, 'Andhra Pradesh'), (telangana, 'Telangana'))


class UserDefaultAddress(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	shipping = models.ForeignKey("UserAddress", null=True,\
					 blank=True, related_name="user_address_shipping_default")
	billing = models.ForeignKey("UserAddress", null=True,\
					blank=True, related_name="user_address_billing_default")

	def __unicode__(self):
		return str(self.user.username)



class UserAddressManager(models.Manager):
	def get_billing_addresses(self, user):
		return super(UserAddressManager, self).filter(billing=True).filter(user=user)

class UserAddress(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	address = models.CharField(max_length=120)
	address2 = models.CharField(max_length=120, null=True, blank=True)
	city = models.CharField(max_length=120)
	state = models.CharField(max_length=120, choices=state_choices, null=True, blank=True)
	country = models.CharField(max_length=120)
	zipcode = models.CharField(max_length=25)
	phone =  models.CharField(max_length=120)
	shipping = models.BooleanField(default=True)
	billing = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __unicode__(self):
		return self.get_address()

	def get_address(self):
		return "%s, %s, %s, %s, %s" %(self.address, self.city, self.state, self.country, self.zipcode)

	objects = UserAddressManager()

	class Meta:
		ordering = ['-updated', '-timestamp']



class UserStripe(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	stripe_id = models.CharField(max_length=120, null=True, blank=True)

	def __unicode__(self):
		return str(self.stripe_id)

#cus_4iMQyUSLNMrCxe
####cus_4iMT2JwLrE8sWx


class EmailConfirmed(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	activation_key = models.CharField(max_length=200)
	confirmed = models.BooleanField(default=False)

	def __unicode__(self):
		return str(self.confirmed)

	def activate_user_email(self):
		#send email here & render a string
		activation_url = "%s%s" %(settings.SITE_URL, reverse("activation_view", args=[self.activation_key]))
		context = {
			"activation_key": self.activation_key,
			"activation_url": activation_url,
			"user": self.user.username,
		}
		message = render_to_string("accounts/activation_message.txt", context)
		subject = "Activate your Email"
		self.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)

	def email_user(self, subject, message, from_email=None, **kwargs):
            s = SMTP()
            s.connect('smtp.webfaction.com')
            s.login('rtxingmail','Reynoldsnext23$')
            print self.user.email
            s.sendmail('contact@smartvizag.com', self.user.email, message)
		#send_mail(subject, message, from_email, [self.user.email], kwargs)




class EmailMarketingSignUp(models.Model):
	email = models.EmailField()
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	#confirmed = models.BooleanField(default=False)

	def __unicode__(self):
		return str(self.email)

myproject/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):

	fullname = models.CharField(max_length=200, null=True, blank=True)
	lastname = models.CharField(max_length=200, null=True, blank=True)
	email = models.CharField(max_length=200, null=True, blank=True)
	phone = models.CharField(max_length=200, null=True, blank=True)
	subject = models.CharField(max_length=200, null=True, blank=True)
	message = models.CharField(max_length=200, null=True, blank=True)
	
	def __unicode__(self):
        	return self.fullname






class Truck(models.Model):
	loading = "Loading"
	unloading = "Unloading"
	unpacking = "Unpacking"
    	truck_choices = ((loading, "Loading"), (unloading, "Unloading"), (unpacking, "Unpacking"))
	post_id = models.CharField(max_length=200, null=True, blank=True)
	from_location = models.CharField(max_length=200, null=True, blank=True)
	to_location = models.CharField(max_length=200, null=True, blank=True)
	capacity = models.CharField(max_length=200, null=True, blank=True)
	scheduled_date = models.DateField(null=True, blank=True)
	posted_by = models.CharField(max_length=200, null=True, blank=True)
	truck_type = models.CharField(max_length=200, choices=truck_choices, null=True, blank=True)
	distance = models.CharField(max_length=200, null=True, blank=True)
	approx_travelling_time = models.CharField(max_length=200, null=True, blank=True)
	truck_image = models.ImageField(null=True, blank=True)
	
	def __unicode__(self):
        	return self.post_id
    	class Meta:
        	verbose_name_plural = 'Truck Details'
    
    	def calc_truck_id(self, x):
        	tnames = "TRUCK"
        	truck = tnames
        
        	post_id = truck +  str(self.id)
        	print "truck id is :", post_id
        	return post_id.upper()

    	def save(self, *args, **kwargs):
        	super(Truck, self).save(*args, **kwargs)
        	self.post_id = self.calc_truck_id(self)
        	super(Truck, self).save(*args, **kwargs)


class Load(models.Model):
	loading = "Loading"
	unloading = "Unloading"
	unpacking = "Unpacking"
    	truck_choices = ((loading, "Loading"), (unloading, "Unloading"), (unpacking, "Unpacking"))
	post_id = models.CharField(max_length=200, null=True, blank=True)
	from_location = models.CharField(max_length=200, null=True, blank=True)
	to_location = models.CharField(max_length=200, null=True, blank=True)
	capacity = models.CharField(max_length=200, null=True, blank=True)
	scheduled_date = models.DateField(null=True, blank=True)
	posted_by = models.CharField(max_length=200, null=True, blank=True)
	truck_type = models.CharField(max_length=200,choices=truck_choices, null=True, blank=True)
	distance = models.CharField(max_length=200, null=True, blank=True)
	approx_travelling_time = models.CharField(max_length=200, null=True, blank=True)
	truck_image = models.ImageField(null=True, blank=True)
	
	def __unicode__(self):
        	return self.post_id
    	class Meta:
        	verbose_name_plural = 'Load Details'
    
    	def calc_load_id(self, x):
        	tnames = "LOAD"
        	load = tnames
        
        	post_id = load +  str(self.id)
        	print "load id is :", post_id
        	return post_id.upper()

    	def save(self, *args, **kwargs):
        	super(Load, self).save(*args, **kwargs)
        	self.post_id = self.calc_load_id(self)
        	super(Load, self).save(*args, **kwargs)

			
class Fm16(models.Model):
	gate1 = "Gate1"
	gate2 = "Gate2"
	gate3 = "Gate3"
    	gate_choices = ((gate1, "Gate1"), (gate2, "Gate2"), (gate3, "Gate3"))
		
			
	
	gate = models.CharField(max_length=200,choices=gate_choices, null=True, blank=True)
	vehicle_no = models.CharField(max_length=200, null=True, blank=True)
	vehicle_load =  models.CharField(max_length=200, null=True, blank=True)
	comments = models.TextField(null=True, blank=True)
	
	g_salary = models.CharField(max_length=200, null=True, blank=True)
	p_tax = models.CharField(max_length=200, null=True, blank=True)
	i_tax_paid = models.CharField(max_length=200, null=True, blank=True)
	bank_interest = models.CharField(max_length=200, null=True, blank=True)
	us_17_2 = models.CharField(max_length=200, null=True, blank=True)
	us_17_3 = models.CharField(max_length=200, null=True, blank=True)
	other_income = models.CharField(max_length=200, null=True, blank=True)
	gpf = models.CharField(max_length=200, null=True, blank=True)
	
	ppf = models.CharField(max_length=200, null=True, blank=True)
	gis = models.CharField(max_length=200, null=True, blank=True)
	lic = models.CharField(max_length=200, null=True, blank=True)
	pli = models.CharField(max_length=200, null=True, blank=True)
	edu_expense = models.CharField(max_length=200, null=True, blank=True)
	hbl_principal = models.CharField(max_length=200, null=True, blank=True)
	mf = models.CharField(max_length=200, null=True, blank=True)
	nsc = models.CharField(max_length=200, null=True, blank=True)
	
	sukanya = models.CharField(max_length=200, null=True, blank=True)
	other_savings_name = models.CharField(max_length=200, null=True, blank=True)
	other_savings = models.CharField(max_length=200, null=True, blank=True)
	mediclaim = models.CharField(max_length=200, null=True, blank=True)
	edu_loan = models.CharField(max_length=200, null=True, blank=True)
	hbl_interest = models.CharField(max_length=200, null=True, blank=True)
	donation = models.CharField(max_length=200, null=True, blank=True)
	other_80_name_1 = models.CharField(max_length=200, null=True, blank=True)
	
	other_80_1 = models.CharField(max_length=200, null=True, blank=True)
	other_80_name_2 = models.CharField(max_length=200, null=True, blank=True)
	other_80_2 = models.CharField(max_length=200, null=True, blank=True)
	house_rent_exempt = models.CharField(max_length=200, null=True, blank=True)
	us_10_14 = models.CharField(max_length=200, null=True, blank=True)
	tax_relief_89 = models.CharField(max_length=200, null=True, blank=True)
	relief_80ccc = models.CharField(max_length=200, null=True, blank=True)
	relief_80ccd = models.CharField(max_length=200, null=True, blank=True)
	
	name_employee = models.CharField(max_length=200, null=True, blank=True)
	desig_employee = models.CharField(max_length=200, null=True, blank=True)
	pan_employee = models.CharField(max_length=200, null=True, blank=True)
	name_employer = models.CharField(max_length=200, null=True, blank=True)
	desig_employer = models.CharField(max_length=200, null=True, blank=True)
	tan_employer = models.CharField(max_length=200, null=True, blank=True)
	pan_employer = models.CharField(max_length=200, null=True, blank=True)
	date_employer_sign = models.CharField(max_length=200, null=True, blank=True)
        office_address = models.TextField(null=True, blank=True)
	place_employer_sign = models.CharField(max_length=200, null=True, blank=True)
	name_employer_father = models.CharField(max_length=200, null=True, blank=True)

        def __unicode__(self):
           return unicode(self.first_name) or u''	
	
##	def __unicode__(self):
##        	return self.first_name
## 


class Enrollment(models.Model):

	canter_jumbo = "Canter Jumbo"
    	canters_mt = "Canters 7.5MT/ 6 Wheel"
    	containers_truck = "Containers Truck"
    	lowbed_trailer = "Low Bed Trailer"
	multiaxle_trailer = "Mulit Axle Trailer"
    	truck_choices = ((canter_jumbo, "Canter Jumbo"), (canters_mt, "Canters 7.5MT/ 6 Wheel"), (containers_truck, "Containers Truck"), (lowbed_trailer, "Low Bed Trailer"), (multiaxle_trailer, "Mulit Axle Trailer"))
	name = models.CharField(max_length=200, null=True, blank=True)
	phone1 = models.CharField(max_length=200, null=True, blank=True)
	phone2 = models.CharField(max_length=200, null=True, blank=True)
	address = models.TextField(null=True, blank=True)
	aadhar_card = models.CharField(max_length=16)
	vehicle_no = models.CharField(max_length=10, null=True, blank=True)
	vehicle_type = models.CharField(max_length=200, choices=truck_choices, null=True, blank=True)
	attach_files = models.ImageField(null=True, blank=True)
	driving_license = models.CharField(max_length=30, null=True, blank=True)
	cbook = models.CharField(max_length=30, null=True, blank=True)

	def __unicode__(self):
        	return self.name
	class Meta:
        	verbose_name_plural = 'Enrollment'


templates/about.html
{% extends "base.html" %}

{% block title %} KK Packers and Movers  {% endblock %}

{% block body_block %}

			<div class="bg-image page-title">
				<div class="container-fluid">
					<a href="#"><h1>ABOUT US</h1></a>
					<div class="pull-right">
						<a href="/"><i class="fa fa-home fa-lg"></i></a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="/about/">About Us</a>
					</div>
				</div>
			</div>

			<div class="container-fluid inner-offset">
				<div class="hgroup text-center wow zoomIn" data-wow-delay="0.3s">
					<h2>FOR ALL YOUR CARGO NEEDS</h2>
					<h1>KK Packers and Movers - THE RIGHT CHOICE</h1>
				</div>            
				<ul class="nav nav-tabs wow fadeIn" data-wow-delay="0.3s" id="myTab">
					<li class="active"><a href="#tab1" data-toggle="tab">WHY CHOOSE US</a></li>
					<li><a href="#tab2" data-toggle="tab">THE MISSION</a></li>
					<li><a href="#tab3" data-toggle="tab">OUR STRATEGY</a></li>
				</ul>

				<div class="tab-content inner-offset wow fadeIn" data-wow-delay="0.3s">
					<div class="tab-pane active" id="tab1">
						<div class="row">
							<div class="col-sm-5">
								<img class="full-width" src="/static/kkpackers-static/media/images/1.jpg" alt="Img">
							</div>
							<div class="col-sm-7">
								<p><strong style="font-size:16px;">HOUSEHOLD, INDUSTRIAL AND DOMESTIC PACKERS & MOVERS ALL OVER INDIA.</strong></p>
								<p>We have registered in ENC, NAVY, PF, ESI, Labour Science, Service Lab Registration and we can supply mini vehicles, heavy vehicles, Trailors and man power.</p>
								<u>For M/s APSTC for import and export aircargo packages transportation from visakhapatnam airport to their ACC Godowns</u>
							</div>
						</div>
					</div>
					<div class="tab-pane" id="tab2">
						<div class="row">
							<div class="col-sm-5">
								<img class="full-width" src="/static/kkpackers-static/media/images/1.jpg" alt="Img">
							</div>
							<div class="col-sm-7 text-block">
								<p><strong>HOUSEHOLD, INDUSTRIAL AND DOMESTIC PACKERS & MOVERS ALL OVER INDIA..</strong></p>
								<p>Authorised Contractors for M/S NTPC Ltd, Simhadri, Vizag for 1 year(from 01-4-2006) for local collection to their material from & around Visakhapatnam</p>
								<u>GAIL(India) Limited: Transportation of mass flow meters for calibration at FCRI Palghat, Kerala from 'N' Different Places at GAIL VSPL & Back.</u>
							</div>
						</div>
					</div>
					<div class="tab-pane" id="tab3">
						<div class="row">
							<div class="col-sm-5">
								<img class="full-width" src="/static/kkpackers-static/media/images/1.jpg" alt="Img">
							</div>
							<div class="col-sm-7 text-block">
								<p><strong>HOUSEHOLD, INDUSTRIAL AND DOMESTIC PACKERS & MOVERS ALL OVER INDIA..</strong></p>
								<p>We have registered in ENC, NAVY, PF, ESI, Labour Science, Service Lab Registration and we can supply mini vehicles, heavy vehicles, Trailors and man power</p>
								<u>GAIL(India) Limited: Transportation of mass flow meters for calibration at FCRI Palghat, Kerala from 'N' Different Places at GAIL VSPL & Back.</u>
							</div>
						</div>
					</div>
				</div>

				
			</div>

			

			<div class="container-fluid partners block-content">
				<div class="hgroup title-space wow fadeInLeft" data-wow-delay="0.3s">
					<h1>TRUSTED partners</h1>
					<h2>HOUSEHOLD, INDUSTRIAL AND DOMESTIC PACKERS & MOVERS</h2>
				</div>
				<div id="partners" class="owl-carousel enable-owl-carousel" data-pagination="false" data-navigation="true" data-min450="2" data-min600="2" data-min768="4">
					<div class="wow rotateIn" data-wow-delay="0.3s"><a href="#"><img src="/static/kkpackers-static/media/partners/1.png" alt="Img"></a></div>
					<div class="wow rotateIn" data-wow-delay="0.3s"><a href="#"><img src="/static/kkpackers-static/media/partners/2.png" alt="Img"></a></div>
					<div class="wow rotateIn" data-wow-delay="0.3s"><a href="#"><img src="/static/kkpackers-static/media/partners/3.png" alt="Img"></a></div>
					<div class="wow rotateIn" data-wow-delay="0.3s"><a href="#"><img src="/static/kkpackers-static/media/partners/4.png" alt="Img"></a></div>
					<div class="wow rotateIn" data-wow-delay="0.3s"><a href="#"><img src="/static/kkpackers-static/media/partners/1.png" alt="Img"></a></div>
					<div class="wow rotateIn" data-wow-delay="0.3s"><a href="#"><img src="/static/kkpackers-static/media/partners/2.png" alt="Img"></a></div>
				</div>
			</div>

{% endblock %}

templates/contact.html
{% extends "base.html" %}

{% block title %} KK Packers and Movers  {% endblock %}

{% block body_block %}

			<div class="bg-image page-title">
				<div class="container-fluid">
					<a href="#"><h1>contact us</h1></a>
					<div class="pull-right">
						<a href="/"><i class="fa fa-home fa-lg"></i></a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="/contactus/">Contact Us</a>
					</div>
				</div>
			</div>

<div style="width: 100%"><iframe width="100%" height="450" src="http://www.mapi.ie/create-google-map/map.php?width=100%&amp;height=450&amp;hl=en&amp;q=rcm%20church%2C%20old%20gajuwaka%2Cvisakhapatnam+(KK%20Packers%20and%20Movers)&amp;ie=UTF8&amp;t=&amp;z=15&amp;iwloc=A&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"><a href="http://www.mapsdirections.info/pl/stworz-mape-google/">mapa google na stronie</a> na <a href="http://www.mapsdirections.info/pl/">Narzędzie Planowania Trasy</a></iframe></div><br />

			<div class="container-fluid block-content">
				<div class="row main-grid">
					<div class="col-sm-4">
						<h4>Head Office</h4>
						<p>Everyday is a new day for us and we work really hard to
							satisfy our customers everywhere.</p>
						<div class="adress-details wow fadeInLeft" data-wow-delay="0.3s">
							<div>
								<span><i class="fa fa-location-arrow"></i></span>
								<div><strong>KK PACKERS & MOVERS</strong><br>D.No 7-11-36,<br>R.C.M Church Left Side<br>BHPV Road, Old Gajuwaka<br>Visakhapatnam-530026(A.P). </div>
							</div>
							<div>
								<span><i class="fa fa-phone"></i></span>
								<div>Ph : 0891-2516328 , 2549577<br/>Cell : 98481 98358 , 96666 98357</div>
							</div>
							<div>
								<span><i class="fa fa-envelope"></i></span>
								<div>kkpackersmovers@yahoo.co.in <br/> kkpackersmovers@rediffmail.com</div>
							</div>
							<div>
								<span><i class="fa fa-clock-o"></i></span>
								<div>24/7 Support</div>
							</div>
						</div>
						<br><br><hr><br>
						<h4>Branch Office</h4>
						<div class="adress-details wow fadeInLeft" data-wow-delay="0.3s">
							<div>
								<span><i class="fa fa-location-arrow"></i></span>
								<div><strong>KK PACKERS & MOVERS</strong><br> HYDERABAD - 75.</div>
							</div>
							<div>
								<span><i class="fa fa-phone"></i></span>
								<div>Cell : 97049 67786</div>
							</div>
							<div>
								<span><i class="fa fa-envelope"></i></span>
								<div>kkpackersmovers@yahoo.co.in <br/> kkpackersmovers@rediffmail.com</div>
							</div>
							<div>
								<span><i class="fa fa-clock-o"></i></span>
								<div>24/7 Support</div>
							</div>
						</div>
					</div>
					<div class="col-sm-8 wow fadeInRight" data-wow-delay="0.3s">
						<h4>SEND us a message</h4>
						<p>We have registered in ENC, NAVY, PF, ESI, Labour Science, Service Lab Registration and we can supply mini vehicles, heavy vehicles, Trailors and man power.</p>
						<div id="success"></div>
						{% if done %}
        <p> Your Message has been forwaded to the respective authorities. Thank You</p>


        {% else %}
						<form novalidate id="contactForm" class="reply-form form-inline" method="post" action="/contactus/" enctype="multipart/form-data">
                    {% csrf_token %}
							<div class="row form-elem">
									
								<div class="col-sm-6 form-elem">
									<div class="default-inp form-elem">
										<i class="fa fa-user"></i>
										<input type="text" name="fullname" id="id_fullname" placeholder="First Name" required="required">
									</div>
									<div class="default-inp form-elem">
										<i class="fa fa-envelope"></i>
										<input type="text" name="email" id="id_email" placeholder="Email Address" required="required">
									</div>
								</div>
								<div class="col-sm-6 form-elem">
									
									<div class="default-inp form-elem">
										<i class="fa fa-phone"></i>
										<input type="text" name="phone" id="id_phone" placeholder="Phone No.">
									</div>
								</div>
							</div>
							<div class="default-inp form-elem">
								<input type="text" name="subject" id="id_subject" placeholder="Subject">
							</div>
							<div class="form-elem default-inp">
								<textarea id="message" id="id_message" placeholder="Message"></textarea>
							</div>
							<div class="form-elem">
								<button type="submit" class="btn btn-success btn-default">send message</button>
							</div>
						</form>
{% endif %}
					</div>
				</div>
			</div>

			{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %} MVGR  {% endblock %}

{% block body_block %}
	        
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
		<center>	<img alt="Bootstrap Image Preview" src="http://nss.ramtej.org/conf2009/images/mvgr1.jpg" align="center" class="img-rounded" /> </center>
		</div>
	</div>
</div>
			
			

{% endblock %} 	       